services:
  api:
    image: ghcr.io/utkar5hm/execstasy-api:main
    container_name: execstasy-api
    restart: always
    env_file:
      - ".env"
  web:
    image: ghcr.io/utkar5hm/execstasy-web:main
    container_name: execstasy-web
    restart: always
    env_file:
      - ".env"
  nginx:
    container_name: execstasy-nginx
    image: nginx:latest
    depends_on:
      - api
      - web
    ports:
      - "127.0.0.1:4000:80"
    volumes:
      - "./nginx/configs:/etc/nginx/sites-enabled"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    restart: always