services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: execstasy-api
    depends_on:
      - redis
    restart: always
    env_file:
      - ".env"
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: execstasy-web
    depends_on:
      - redis
    restart: always
    env_file:
      - ".env"
  redis:
    container_name: execstasy-redis
    image: redis:alpine
    restart: always
  nginx:
    container_name: execstasy-nginx
    image: nginx:latest
    depends_on:
      - api
      - web
    ports:
      - "127.0.0.1:4000:80"
    volumes:
      - "./nginx/configs:/etc/nginx/sites-enabled"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    restart: always
  db:
    container_name: execstasy-postgres
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "delulup4ss"
      POSTGRES_DB: "execstasy"
    volumes:
      - "./db_data:/var/lib/postgresql/data"