services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: execstasy-api
    restart: always
    env_file:
      - "app.env"
    environment:
      - API_DEBUG=FALSE
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    container_name: execstasy-web
    restart: always
    # env_file:
      # - web/.env
  nginx:
    container_name: execstasy-nginx
    image: nginx:latest
    depends_on:
      - api
      - web
    ports:
      - "127.0.0.1:4000:80"
    volumes:
      - "./nginx/configs:/etc/nginx/sites-enabled"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    restart: always